In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('student_data.csv')

In [6]:
df.groupby('placement_status')['placement_status'].agg('count')

placement_status
Not Placed    1644
Placed        8356
Name: placement_status, dtype: int64

In [7]:
df.groupby('placement_status')['exam_score'].agg('mean')

placement_status
Not Placed    59.804653
Placed        91.996556
Name: exam_score, dtype: float64

In [8]:
df.groupby('placement_status')['study_hours'].agg('mean')

placement_status
Not Placed    3.130170
Placed        6.552178
Name: study_hours, dtype: float64

In [12]:
df.groupby('exam_score')['study_hours'].agg('mean')

exam_score
26.67     1.000000
26.89     1.000000
27.82     1.000000
31.41     1.000000
31.43     2.000000
            ...
99.96     7.000000
99.97     7.000000
99.98     7.000000
99.99     6.666667
100.00    8.078977
Name: study_hours, Length: 3563, dtype: float64

In [19]:
def grades(x):
  if x >= 90:
    return "A"
  elif x >= 80:
    return "B"
  elif x >= 70:
    return "C"
  else:
    return "D"

In [21]:
df['grades']=df['exam_score'].apply(grades)
df

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status,grades
0,7,56,8,7,10,62,100.00,Placed,A
1,4,69,5,3,8,56,100.00,Placed,A
2,11,60,7,6,10,45,100.00,Placed,A
3,8,99,9,8,4,55,90.17,Placed,A
4,5,52,8,6,8,40,78.82,Placed,C
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,D
9996,7,98,6,9,4,87,100.00,Placed,A
9997,10,44,8,5,10,37,95.94,Placed,A
9998,10,75,7,5,8,52,88.61,Placed,B
9999,2,70,6,11,16,52,78.96,Placed,C